function distanceMeters(lat1,lon1,lat2,lon2){const R=6371000,rad=Math.PI/180,dLat=(lat2-lat1)*rad,dLon=(lon2-lon1)*rad;const a=Math.sin(dLat/2)**2+Math.cos(lat1*rad)*Math.cos(lat2*rad)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(a))}
function nodeStorageKey(){return 'sutra_geofence_seen_'+(SutraAuth.user().email||'guest').toLowerCase()}
function seenNodes(){try{return JSON.parse(localStorage.getItem(nodeStorageKey())||'[]')}catch{return[]}}
function markSeen(id){const x=seenNodes();if(!x.includes(id)){x.push(id);localStorage.setItem(nodeStorageKey(),JSON.stringify(x))}}
function playChime(){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.setValueAtTime(660,c.currentTime);o.frequency.exponentialRampToValueAtTime(990,c.currentTime+.16);g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.08,c.currentTime+.03);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.32);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.34)}catch(e){}}
function showGeofenceStatus(n,distance,status='LOCKED'){const panel=document.getElementById('geofenceStatus');if(!panel)return;panel.innerHTML=`<div class="geo-status-row"><div><span class="tag">GEOFENCE · ${n.radius}M</span><h3>${n.emoji||'📍'} ${n.name}</h3><p>${n.city}, ${n.state} · ${n.category}</p></div><div class="geo-distance"><strong>${Math.round(distance)}m</strong><span>current distance</span></div></div><div class="geo-status-meta"><span>Radius: <b>${n.radius}m</b></span><span>Status: <b class="${status==='UNLOCKED'?'status-good':''}">${status}</b></span><span>Location accuracy: <b id="geoAccuracy">—</b></span></div>`}
function unlockNode(n,distance){const first=!seenNodes().includes(n.id);markSeen(n.id);playChime();if(first)SutraWallet.add(10,`Heritage Node discovered: ${n.name}`);localStorage.setItem('sutra_current_context',JSON.stringify({city:n.city,state:n.state,node:n.name,nodeId:n.id,updated:new Date().toISOString()}));SutraJourney.add(n.city,n.state,n.name,'geofence');showGeofenceStatus(n,distance,'UNLOCKED');const panel=document.getElementById('nodeUnlockPanel');if(panel){panel.classList.add('open');panel.innerHTML=`<div><span class="tag">HERITAGE NODE UNLOCKED</span><h2>${n.name}</h2><p><b>You are ${Math.round(distance)}m away.</b> · ${n.city}, ${n.state}</p><p>${n.shortStory}</p><a class="btn btn-primary" href="ar.html?node=${encodeURIComponent(n.id)}">Start Heritage Micro-Quest →</a><a class="btn btn-ghost" href="ai.html?node=${encodeURIComponent(n.id)}" style="margin-left:8px">Ask Sutra about this place</a></div>`}}
function validatePosition(pos,previous){const accuracy=Number(pos.coords.accuracy||999);if(accuracy>100){toast('Location accuracy is too low for a reliable 50m quest. Move to an open area and try again.');return false}if(previous){const d=distanceMeters(previous.lat,previous.lng,pos.coords.latitude,pos.coords.longitude);const dt=(pos.timestamp-previous.time)/1000;if(dt>0&&d/dt>60){toast('Movement check failed — the reported speed is inconsistent with a normal walking trip.');return false}}return true}
let lastPosition=null,watchId=null;
function processPosition(pos){if(!SutraSettings.locationEnabled()){toast('Location access is off in your privacy settings.');return}if(!validatePosition(pos,lastPosition))return;lastPosition={lat:pos.coords.latitude,lng:pos.coords.longitude,time:pos.timestamp};const nodes=(window.SUTRA_GEOFENCE_NODES||[]).map(n=>({...n,distance:distanceMeters(pos.coords.latitude,pos.coords.longitude,n.lat,n.lng)})).sort((a,b)=>a.distance-b.distance);const closest=nodes[0];if(closest){showGeofenceStatus(closest,closest.distance,closest.distance<=closest.radius?'UNLOCKED':'LOCKED');const acc=document.getElementById('geoAccuracy');if(acc)acc.textContent=`±${Math.round(pos.coords.accuracy)}m`;if(closest.distance<=closest.radius&&!seenNodes().includes(closest.id))unlockNode(closest,closest.distance)}}
function startGeofenceWatch(){if(!SutraSettings.locationEnabled()){toast('Enable Location Access in Profile to use Heritage Radar.');return}if(!navigator.geolocation){toast('Location is not supported by this browser.');return}toast('Heritage radar is listening for 50m nodes…');watchId=navigator.geolocation.watchPosition(processPosition,()=>toast('Location permission was not granted. You can still use Demo Unlock.'),{enableHighAccuracy:true,maximumAge:5000,timeout:15000})}
function stopGeofenceWatch(){if(watchId!==null&&navigator.geolocation){navigator.geolocation.clearWatch(watchId);watchId=null}toast('Heritage radar stopped.')}
function checkNearbyHeritage(){if(!SutraSettings.locationEnabled()){toast('Enable Location Access in Profile to use Heritage Radar.');return}if(!navigator.geolocation){toast('Location is not supported by this browser.');return}navigator.geolocation.getCurrentPosition(processPosition,()=>toast('Location permission was not granted. You can still use Demo Unlock.'),{enableHighAccuracy:true,maximumAge:0,timeout:15000})}
function simulateHeritageUnlock(){const n=(window.SUTRA_GEOFENCE_NODES||[])[0];if(!n)return;const d=42;localStorage.setItem('sutra_demo_location',JSON.stringify({lat:n.lat,lng:n.lng,accuracy:5,simulated:true}));unlockNode(n,d);toast('Demo location active · 42m from Charminar')}
window.startGeofenceWatch=startGeofenceWatch;window.stopGeofenceWatch=stopGeofenceWatch;window.checkNearbyHeritage=checkNearbyHeritage;window.simulateHeritageUnlock=simulateHeritageUnlock;
