const SUTRA_HERITAGE=[
{id:'node-1',name:'Charminar',city:'Hyderabad',state:'Telangana',district:'Hyderabad',lat:17.3616,lng:78.4747,category:'Monument',emoji:'🕌',radius:50,story:'Built in 1591 by Sultan Muhammad Quli Qutb Shah, Charminar became the symbolic centre of Hyderabad. The surrounding old city still connects the monument to bazaars, food and craft.',shortStory:'A Deccan landmark at the heart of Hyderabad’s living old city.',image:'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80',verification:'Verified heritage content',sources:[{name:'Telangana Tourism — Charminar',url:'https://tourism.telangana.gov.in/attractions/charminar'}],quest:{type:'Quiz',question:'Which dynasty commissioned the Charminar?',options:['Qutb Shahi dynasty','Mughal dynasty','Vijayanagara dynasty','Asaf Jahi dynasty'],answer:0,reward:30},artisan:{name:'Ayesha Begum',craft:'Lac bangle maker',experience:'Old-city craft walk',years:'15+ years'}},
{id:'node-2',name:'Amber Fort',city:'Jaipur',state:'Rajasthan',district:'Jaipur',lat:26.9855,lng:75.8513,category:'Monument',emoji:'🏰',radius:50,story:'Amber Fort is a hilltop complex of courtyards, gateways and palaces associated with the Kachwaha rulers of Amber. Its architecture combines Rajput forms with Mughal influences.',shortStory:'A hilltop fort where Rajput architecture meets layered court culture.',image:'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1200&q=80',verification:'Curated heritage content',sources:[{name:'Rajasthan Tourism',url:'https://www.tourism.rajasthan.gov.in/amber-palace.html'}],quest:{type:'Quiz',question:'Amber Fort is located in which city?',options:['Jaipur','Jodhpur','Udaipur','Jaisalmer'],answer:0,reward:30},artisan:{name:'Mohan Lal',craft:'Blue pottery artisan',experience:'Craft demonstration',years:'20+ years'}},
{id:'node-3',name:'Hampi',city:'Hampi',state:'Karnataka',district:'Vijayanagara',lat:15.335,lng:76.46,category:'Living Heritage',emoji:'🏛️',radius:50,story:'Hampi preserves the remains of the Vijayanagara capital, including temples, royal and civic structures, markets and water systems across a dramatic boulder landscape.',shortStory:'A vast archaeological landscape where city, temple and river shaped one another.',image:'https://images.unsplash.com/photo-1600112356915-089abb8fc71a?auto=format&fit=crop&w=1200&q=80',verification:'UNESCO World Heritage content',sources:[{name:'UNESCO — Group of Monuments at Hampi',url:'https://whc.unesco.org/en/list/241'}],quest:{type:'Quiz',question:'Hampi was the capital of which historic empire?',options:['Vijayanagara Empire','Maurya Empire','Gupta Empire','Chola Empire'],answer:0,reward:30},artisan:{name:'Ravi Kumar',craft:'Banana-fibre craft',experience:'Local craft trail',years:'12+ years'}},
{id:'node-konark',name:'Sun Temple, Konark',city:'Konark',state:'Odisha',district:'Puri',lat:19.8876,lng:86.0945,category:'Monument',emoji:'☀️',radius:50,story:'The 13th-century Sun Temple at Konark is conceived as Surya’s monumental chariot, with carved wheels, horses and scenes of historical life.',shortStory:'A monumental stone chariot that turns architecture into a story.',image:'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80',verification:'UNESCO World Heritage content',sources:[{name:'UNESCO — Sun Temple, Konârak',url:'https://whc.unesco.org/en/list/246'}],quest:{type:'Quiz',question:'The Sun Temple at Konark represents the chariot of which deity?',options:['Surya','Shiva','Vishnu','Indra'],answer:0,reward:30},artisan:{name:'Madhuri Behera',craft:'Pattachitra artist',experience:'Pattachitra studio visit',years:'18+ years'}},
{id:'node-4',name:'Kutch Craft Trail',city:'Kutch',state:'Gujarat',district:'Kutch',lat:23.7337,lng:69.8597,category:'Craft',emoji:'🧵',radius:50,story:'Kutch is known for embroidery and textile traditions carried through families and communities. A heritage trail can connect the object to the makers, techniques and stories behind it.',shortStory:'A craft landscape where patterns carry memory across generations.',image:'https://images.unsplash.com/photo-1595658658481-d53d3f999875?auto=format&fit=crop&w=1200&q=80',verification:'Curated cultural content',sources:[{name:'Gujarat Tourism',url:'https://www.gujarattourism.com/'}],quest:{type:'Quiz',question:'Which craft tradition is strongly associated with Kutch?',options:['Embroidery','Kathakali','Muga silk','Phulkari'],answer:0,reward:30},artisan:{name:'Fatima Khatri',craft:'Ajrakh textile artisan',experience:'Block-print workshop',years:'22+ years'}}
];
window.SUTRA_HERITAGE=SUTRA_HERITAGE;
window.SUTRA_GEOFENCE_NODES=SUTRA_HERITAGE;
